### ISSUE TITLE
ContextualVersionConflict botocore error

### ISSUE THREAD

**Issue by mtbvang** [aws/aws-encryption-sdk-cli#176]
I have a Dockerfile where I am installing aws-encryption-sdk-cli with the command below.

```
RUN pip install pip install aws-encryption-sdk==1.4.1 aws-encryption-sdk-cli==1.1.7 requests \
    && pip uninstall --yes botocore \
    && pip install botocore==1.17.37
```
Whenever there is a new fix version of botocore I get the following error when trying to run `aws-encryption-cli` and I need to bump the botocore version up to get rid of the error:

`ContextualVersionConflict("botocore 1.17.34", "botocore<1.18.0,>=1.17.37", "set(['boto3'])")`

**Comment by MatthewBennington** [comment]
Hi!

The error you're seeing is unrelated to the AWS Encryption SDK CLI. It's caused by the lines you have locking `botocore` to a specific version. aws-encryption-sdk-cli requires `boto3`, so whenever `boto3` and `botocore` update, you're getting the new `boto3` but pinning on the old `botocore`.

I would recommend removing the lines locking `botocore`'s version:
```
&& pip uninstall --yes botocore \
&& pip install botocore==1.17.37
```

Additionally, you probably don't need both the `aws-encryption-sdk` and `aws-encryption-sdk-cli` packages.

**Comment by mtbvang** [comment]
@MatthewBennington Thanks for the answer! I originally added the botocore uninstall and install lines because I of the error. I've reverted and done as you suggested and will see if I get errors again.
