### ISSUE TITLE
Why we can use only the Key ARN when decrypting?

### ISSUE THREAD

**Issue by januswel** [aws/aws-encryption-sdk-cli#202]
https://github.com/aws/aws-encryption-sdk-cli#master-key-provider

> If using aws-kms to decrypt and specifying a key, you must use a key ARN; key ids, alias names, and alias ARNs are not supported.

On the other hand, we can use key ids and key aliases when we encrypting.
I believe this design is very confusing.
Tell me why aws-encryption-cli support *only key ARNs*?

And why don't you show what the users should do in the error message, when the uses intended to use key ids / key aliases?

**Comment by farleyb-amazon** [comment]
Hi,

The aws-encryption-cli, and all other implementations of the AWS Encryption SDK, require ARNs on decrypt as a safety measure to ensure that they only decrypt messages with an explicitly trusted set of keys. Due to implementation details in KMS and the Encryption SDK, the metadata stored with ciphertexts contains key ARNs, so this is what we require on decrypt.

If you want to decrypt without specifying key ARNs, you can use the  `discovery=true` attribute of the `--wrapping-keys` parameter which will attempt decryption regardless of which key was used to encrypt.

> And why don't you show what the users should do in the error message, when the uses intended to use key ids / key aliases?

Thanks for the feedback, we’ll look into making the error messages more clear.

Thanks,
Ben
